[package]
name = "license-contract"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
zk-citadel = { path = "../core"}
dusk-plonk = { version = "0.20", default-features = false, features = ["rkyv-impl", "alloc"] }
rand_core = { version = "0.6", default-features=false, features = ["getrandom"] }
reqwest = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
build-print = "0.1.1"
sha2 = { version = "0.10.8", default-features = false }
