on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main

  wallet_code_analysis:
    name: Wallet Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy -p zk-citadel-wallet --all-targets -- -D warnings
      - run: make test-wallet

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  build_benches:
    name: Build Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: make bench BENCH_ARGS=--no-run

  test_std:
    name: Stable toolchain release tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: make test-core
      - run: make test-contract
      - run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --features zk
