on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  build_benches:
    name: Build Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench --no-run

  test_std:
    name: Stable toolchain tests
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main

  test_no_std:
    name: Stable toolchain no_std tests
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --no-default-features
      
